// <auto-generated />
using System;
using ApiCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241101221520_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiCore.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("UAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 11, 2, 3, 45, 15, 554, DateTimeKind.Local).AddTicks(390),
                            Name = "Ayesha",
                            Salary = 45000.0,
                            UAN = "qwertyuiop12345"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2024, 11, 2, 3, 45, 15, 554, DateTimeKind.Local).AddTicks(405),
                            Name = "Ayesha",
                            Salary = 45000.0,
                            UAN = "poiuytrewq54321"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2024, 11, 2, 3, 45, 15, 554, DateTimeKind.Local).AddTicks(407),
                            Name = "Ayesha",
                            Salary = 45000.0,
                            UAN = "mnbvcxz12345"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
